/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'


export default function HeadWithGoggles(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/HeadWithGoggles.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      
      <mesh material={materials.Skin} geometry={nodes.Face.geometry} />
      <mesh material={materials.HairBase} geometry={nodes.HairExtrude.geometry} />
      <mesh material={materials.Hair} geometry={nodes.Brows.geometry} />
      <mesh material={materials.Hair} geometry={nodes.Hairs.geometry} />
      <mesh material={materials.Beard} geometry={nodes.Beard.geometry} />
      <group position={[0, 0.29, 1.12]} scale={[0.68, 0.7, 0.63]}>
        <mesh material={materials.Base} geometry={nodes.Cube002.geometry} />
        <mesh material={materials.Shadow} geometry={nodes.Cube002_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/HeadWithGoggles.glb')
